repos:
  -   repo: https://github.com/ambv/black
      rev: stable
      hooks:
        - id: black
          language_version: python3.8
          exclude: pricing_algorithm/algorithm/utils/competitor_cleaning_imputation_scorings.py
  -   repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v1.2.3
      hooks:
        - id: flake8
  -   repo: https://github.com/timothycrosley/isort
      rev: 5.7.0
      hooks:
      -   id: isort
          args: ["--profile", "black"]